name: flutter_exam
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.4
  audioplayers: ^0.20.1
  rflutter_alert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/xylophone/
    - assets/StoneGame/
    - assets/images/
    - assets/images/dice/
    - assets/images/micard/
    - assets/images/Magicball/
    - assets/images/Destini/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

